fail_fast: true
repos:
  - repo: builtin
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_validate
        args:
          - --hook-config=--tf-path=tofu
      - id: terraform_fmt
        args:
          - --hook-config=--tf-path=tofu
          - --args=-write=true
      - id: terraform_tflint
        args:
          - --hook-config=--tf-path=tofu
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_trivy
        args:
          - --args=--config=__GIT_WORKING_DIR__/trivy.yml
